Feature: READMEを整備する
tsukuba-websci/UrnBasedDynamicNetworkModel pull request #8
Opened 2023-09-12 06:47 UTC by krmr73

## WHAT
- READMEを更新した
- English versionを追加した

2023-09-12 06:52 UTC, krmr73 commented
@ciaran-regan-ie I would like you to check the English version of the writing. And please let me know if there is anything additional I should write about.

2023-09-12 08:14 UTC, ciaran-regan-ie commented on README-en.md
> +## Abstruct
Should say
Abstract

2023-09-12 08:14 UTC, ciaran-regan-ie commented on README-en.md
> +This is the repository for the article "Simulating Emergence of Novelties Using Agent-Based Models", which was submitted to PLOSONE.
I think PLOS ONE is two words

2023-09-12 08:15 UTC, ciaran-regan-ie commented on README-en.md
> +Some analyses require Python environment.
analysis

2023-09-12 08:21 UTC, ciaran-regan-ie requested changes
Great work! A few minor comments, but LGTM!

2023-09-13 09:05 UTC, ciaran-regan-ie approved these changes

2023-09-13 09:05 UTC, merged